config/routes.rb
Rails.application.routes.draw do
  resources :nominations

  resources :candidates

  resources :parties

  resources :mps
  resources :mlas

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_many :nominations
	validates_presence_of :name
end

app/models/mla.rb
class Mla < Seat
end

app/models/mp.rb
class Mp < Seat
end

app/models/nomination.rb
class Nomination < ActiveRecord::Base
  
  belongs_to :candidate
  belongs_to :seat
  belongs_to :party

end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :nominations
	validates_presence_of :name
	validates_uniqueness_of :name, case_sensitive: false
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  has_many :nominations
	validates_presence_of :name, :type

	validates_uniqueness_of :name, case_sensitive: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :dob)
    end
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  before_action :set_nomination, only: [:show, :edit, :update, :destroy]

  # GET /nominations
  # GET /nominations.json
  def index
    @nominations = Nomination.all
  end

  # GET /nominations/1
  # GET /nominations/1.json
  def show
  end

  # GET /nominations/new
  def new
    @nomination = Nomination.new
  end

  # GET /nominations/1/edit
  def edit
  end

  # POST /nominations
  # POST /nominations.json
  def create
    @nomination = Nomination.new(nomination_params)

    respond_to do |format|
      if @nomination.save
        format.html { redirect_to @nomination, notice: 'Nomination was successfully created.' }
        format.json { render :show, status: :created, location: @nomination }
      else
        format.html { render :new }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nominations/1
  # PATCH/PUT /nominations/1.json
  def update
    respond_to do |format|
      if @nomination.update(nomination_params)
        format.html { redirect_to @nomination, notice: 'Nomination was successfully updated.' }
        format.json { render :show, status: :ok, location: @nomination }
      else
        format.html { render :edit }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nominations/1
  # DELETE /nominations/1.json
  def destroy
    @nomination.destroy
    respond_to do |format|
      format.html { redirect_to nominations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nomination
      @nomination = Nomination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nomination_params
      params.require(:nomination).permit(:candidate_id, :seat_id, :party_id, :year)
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name)
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.dob %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @candidate.dob %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elections</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nominations/_form.html.erb
<%= form_for(@nomination) do |f| %>
  <% if @nomination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nomination.errors.count, "error") %> prohibited this nomination from being saved:</h2>

      <ul>
      <% @nomination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :candidate_id %><br>
    <%= f.text_field :candidate_id %>
  </div>
  <div class="field">
    <%= f.label :seat_id %><br>
    <%= f.text_field :seat_id %>
  </div>
  <div class="field">
    <%= f.label :party_id %><br>
    <%= f.text_field :party_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nominations/edit.html.erb
<h1>Editing nomination</h1>

<%= render 'form' %>

<%= link_to 'Show', @nomination %> |
<%= link_to 'Back', nominations_path %>

app/views/nominations/index.html.erb
<h1>Listing nominations</h1>

<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Seat</th>
      <th>Party</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nominations.each do |nomination| %>
      <tr>
        <td><%= nomination.candidate %></td>
        <td><%= nomination.seat %></td>
        <td><%= nomination.party %></td>
        <td><%= nomination.year %></td>
        <td><%= link_to 'Show', nomination %></td>
        <td><%= link_to 'Edit', edit_nomination_path(nomination) %></td>
        <td><%= link_to 'Destroy', nomination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nomination', new_nomination_path %>

app/views/nominations/new.html.erb
<h1>New nomination</h1>

<%= render 'form' %>

<%= link_to 'Back', nominations_path %>

app/views/nominations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @nomination.candidate %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @nomination.seat %>
</p>

<p>
  <strong>Party:</strong>
  <%= @nomination.party %>
</p>

<p>
  <strong>Year:</strong>
  <%= @nomination.year %>
</p>

<%= link_to 'Edit', edit_nomination_path(@nomination) %> |
<%= link_to 'Back', nominations_path %>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mla_or_mp %><br>
    <%= f.text_field :mla_or_mp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.name %></td>
        <td><%= seat.category %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seat.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @seat.type %>
</p>

<%= link_to 'Edit', [:edit , @seat] %> |
<%= link_to 'Back', seats_path %>